version: "3"

services:
  honeypot:
    image: cowrie/cowrie
    container_name: ai-cydece-ssh_honeypot
    ports:
      - "2222:2222"

  tcpdump:
    image: nicolaka/netshoot
    container_name: ai-cydece-tcpdump
    command: tcpdump -i any -w /data/pcaps/capture.pcap
    volumes:
      - ./data:/data
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
